### ISSUE TITLE
Add Digit Grouping

### ISSUE THREAD

**Issue by fsargent** [lucas-tulio/unix-time-clock-widget#1]
For easier readability, and determination between K, M and G seconds, can we add either spaces, or 'digit group separators' every three digits?
https://en.wikipedia.org/wiki/Decimal_mark#Digit_grouping
https://developer.android.com/reference/java/text/DecimalFormat.html

**Comment by lucas-tulio** [comment]
Thanks for the suggestion. I'd prefer to add it as an option though: the user may tap the clock to toggle the digit separators (either spaces, ":" or "."), so you can always go back to the original view. I'll try to address this feature in the following weeks, but feel free to contribute if you want. Thanks!

**Comment by lucas-tulio** [comment]
@fsargent Done in 6dd5700e19c4368477f45aba3bca18ad47679222.

Updating apk in the store.
